---
- hosts: 172.31.29.80
  become: yes
  tasks: 
  - include_tasks: createFile.yml
  - name: install web server on ansible hosts/node
    apt: 
      name: apache2
      state: present
  - name: I want to copy myindex from master to node 
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
  - name: I want to download from internet jenkins file
    get_url:
      url: https://get.jenkins.io/war-stable/2.332.1/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes