---
- hosts: 172.31.29.80
  become: yes
  tasks: 
  - name: I want to install tree, git and wget
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - tree
      - git
      - wget
   