---
- hosts: all
  become: yes
  tasks:
    - name: installing web server
      apt:
        name: apache2
        state: present
    - name: starting apache2 web server
      service:
        name: apache2
        state: started