---
- hosts: myWebServers
  become: yes
  tasks:
    - name: installing web server
      apt:
        name: apache2
        state: present
      when: ansible_os_family =="Debian"
    - name: starting apache2 web server
      service:
        name: apache2
        state: started
      when: ansible_os_family =="Debian"
    - name: installing web server on only redhat node
      yum:
        name: httpd
        state: present
      when: ansible_os_family =="RedHat"
    - name: I want to start web server on only ansible redhat node
      service:
        name: httpd
        state: started
      when: ansible_os_family =="RedHat"