---
- hosts: all
  become: yes
  tasks:
    - name: installing web server
      apt:
        name: apache2
        state: present
      when: ansible_os_family =="Debian"
    - name: starting apache2 web server
      service:
        name: apache2
        state: started
      when: ansible_os_family =="Debian"