---
# tasks file for mytomcat8onubuntu16
- include_tasks: installJava.yml
- include_tasks: createTomcatUser.yml
- include_tasks: installTomcat.yml
- include_tasks: updatePermissions.yml
- include_tasks: createServiceFile.yml
- include_tasks: startTomcat.yml
- include_tasks: tomcatWebManagement
- include_tasks: reStartTomcat.yml