---
- name: copy tomcat user file into node side
  template:
    src: teplate/mytomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
- name: copy context file into node side
  template:
    src: teplate/manager-context-file.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml
- name: copy host context file into node side
  template:
    src: teplate/host-manager-context-file.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml